package com.example;

public class DemoMemoProvider {
    public String getMemo(){
        String memo = new String();

        memo = "[\n" +
                "  {\n" +
                "    \"id\": \"4\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/kah4n8ffbz2i6eu/color-correct-coffee.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/q13febof58oc8ha/color-correct-coffee-thumb.jpg\",\n" +
                "    \"author\": \"Human Resources\",\n" +
                "    \"title\": \"Notice on Coffee Breaks\",\n" +
                "    \"published_date\": \"2013-06-20T00:00:00.000Z\",\n" +
                "    \"body\": \"Bacon ipsum dolor amet ground round kevin turducken landjaeger, cow pig drumstick capicola ham shank biltong venison frankfurter bacon. Pancetta beef salami, tri-tip short loin bacon kevin landjaeger ball tip shoulder corned beef. Doner shankle tongue, drumstick alcatra strip steak kevin turkey tri-tip flank frankfurter meatball biltong kielbasa. Beef ribs brisket shoulder t-bone. Biltong fatback ham hock bresaola salami tongue corned beef filet mignon pork capicola jerky. Turkey short ribs pig, prosciutto kevin andouille pork loin filet mignon landjaeger venison capicola. Hamburger prosciutto beef pork loin doner brisket.<br><br>Venison tongue shank jowl, turkey andouille meatball. Flank corned beef doner landjaeger, meatball kevin sausage boudin swine tongue shankle ground round tri-tip bacon. Sausage bacon shankle porchetta, boudin brisket tri-tip drumstick picanha flank ball tip ribeye cow turkey salami. Pork chop spare ribs chicken meatloaf. Landjaeger ball tip beef ribs kielbasa pork loin.<br><br>Sincerely,<br> HR team <br><br> Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"2\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/u48pkqmn9mk1iii/work-station-straight-on-view.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/pjwdcbsj3tsl18n/work-station-straight-on-view-thumb.jpg\",\n" +
                "    \"author\": \"Management\",\n" +
                "    \"title\": \"Workstation Ethics\",\n" +
                "    \"published_date\": \"2013-01-19T00:00:00.000Z\",\n" +
                "    \"body\": \"<strong>Subject:</strong>Clean Desk Policy<br><br>Pork belly chicken andouille fatback tenderloin kielbasa short loin pastrami cupim venison. Beef pastrami shoulder cupim chicken, venison shank tenderloin jowl brisket beef ribs. Jowl pastrami tail pork loin shank sirloin turducken meatball rump fatback cow hamburger kielbasa. Shank strip steak tri-tip hamburger pancetta tenderloin.<br><br><em>The Management</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"11\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/a25tcv8bynpsa98/fireworks-viewing.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/jxzz0x5uwar6r8r/fireworks-viewing-thumb.jpg\",\n" +
                "    \"author\": \"Human Resources\",\n" +
                "    \"title\": \"Fireworks Viewing\",\n" +
                "    \"published_date\": \"2013-06-19T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger tri-tip bacon t-bone beef meatloaf short ribs brisket pig pork chop kielbasa. Bacon doner jerky prosciutto, kevin meatball pancetta kielbasa chuck ham hock jowl pig shank tail. Corned beef rump shoulder jowl porchetta pork chop shank swine strip steak chicken alcatra short ribs boudin pork belly. Ball tip kevin meatloaf hamburger meatball ham hock cow, prosciutto fatback chicken drumstick. Meatloaf andouille tri-tip alcatra fatback jowl shank ham filet mignon ham hock jerky venison short ribs meatball. Ball tip biltong alcatra andouille, short ribs cupim pig.<br><br>Sincerely,<br>HR Team<br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"3\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/t11zm2gxl0unkro/update-policy.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/dc43dhk7vhfmf0g/update-policy-thumb.jpg\",\n" +
                "    \"author\": \"Human Resources\",\n" +
                "    \"title\": \"Notice on Update of Policies\",\n" +
                "    \"published_date\": \"2013-05-10T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Venison drumstick spare ribs, pig ribeye cupim shankle corned beef andouille chuck. Tail doner pancetta meatloaf chicken shank biltong swine tenderloin boudin chuck pork belly turducken cow spare ribs. Pork swine pig meatloaf leberkas. Cow brisket alcatra strip steak ball tip. Swine pork loin prosciutto tail beef picanha turducken alcatra bacon strip steak.<br><br>Sincerely,<br>HR Team<br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"1\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/rtgs3w8h8jvaw14/go-green.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/u6gsj5m6xvcgjdl/go-green-thumb.jpg\",\n" +
                "    \"author\": \"Management\",\n" +
                "    \"title\": \"Go Green!\",\n" +
                "    \"published_date\": \"2013-05-02T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>The Management</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"5\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/k8u8jtav96kf8gx/irish-hands.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/ohnjdld4tcgo5o7/irish-hands-thumb.jpg\",\n" +
                "    \"author\": \"Mark Richardson\",\n" +
                "    \"title\": \"Meeting Summary\",\n" +
                "    \"published_date\": \"2013-03-19T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>Mark Richardson</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"7\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/e3on1t71rew34gc/uniform-policy.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/jie8q7npdqr01qk/uniform-policy-thumb.jpg\",\n" +
                "    \"author\": \"Human Resources\",\n" +
                "    \"title\": \"Dress Code\",\n" +
                "    \"published_date\": \"2013-01-16T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>Human Resources</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"8\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/oxhy9o2p7vznn4n/recreation.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/07hlwdn93exv0tm/recreation-thumb.jpg\",\n" +
                "    \"author\": \"Anna Valerie\",\n" +
                "    \"title\": \"Practice at the Recreation Room\",\n" +
                "    \"published_date\": \"2013-01-15T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>Anna Valerie</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"9\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/mn8wb5lz8pj0bce/traffic.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/yrb1d1a0m0gtjim/traffic-thumb.jpg\",\n" +
                "    \"author\": \"Management\",\n" +
                "    \"title\": \"Traffic Advisory\",\n" +
                "    \"published_date\": \"2013-01-14T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>The Management</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  },\n" +
                "  {\n" +
                "    \"id\": \"10\",\n" +
                "    \"photo\": \"https://dl.dropboxusercontent.com/s/1tmxnhqn3282bws/transportation.jpg\",\n" +
                "\t\"thumb\": \"https://dl.dropboxusercontent.com/s/chv3nm2pjxnynv7/transportation-thumb.jpg\",\n" +
                "    \"author\": \"Management\",\n" +
                "    \"title\": \"Transportation Allowance\",\n" +
                "    \"published_date\": \"2013-01-13T00:00:00.000Z\",\n" +
                "    \"body\": \"Landjaeger bacon pork loin t-bone, kielbasa bresaola flank meatloaf alcatra prosciutto fatback chicken short ribs tenderloin ball tip. Corned beef bresaola shankle tenderloin. Jerky strip steak ribeye bresaola biltong ball tip boudin sirloin turducken ham hock picanha hamburger tenderloin. Short ribs jerky pork chop fatback boudin kevin brisket t-bone cupim capicola pastrami picanha pork pancetta. Rump prosciutto ball tip corned beef picanha capicola pork t-bone, alcatra kevin.<br><br>Bacon ipsum dolor amet pork chop shoulder jerky cupim. Flank filet mignon bacon chicken spare ribs beef landjaeger cupim. Beef leberkas chicken spare ribs chuck, frankfurter pancetta. Jowl andouille tri-tip tail. Leberkas porchetta corned beef chuck picanha, jowl kielbasa cow. Drumstick jowl pancetta, salami ham pig brisket hamburger ball tip shank pork chop turducken sausage fatback. Tail corned beef shank shoulder.<br><br>Turkey porchetta short ribs tail doner. Shoulder meatball alcatra ham hock cow shankle biltong turducken chicken spare ribs boudin. Meatball rump biltong, tri-tip jowl beef pig pork picanha meatloaf turkey drumstick alcatra turducken beef ribs. Tenderloin doner andouille cupim picanha pig beef ribs strip steak swine turducken pork pork loin beef jowl hamburger. Cupim venison tri-tip swine filet mignon jowl boudin drumstick salami. Hamburger andouille ground round, kevin tri-tip meatball chicken. Cupim short loin filet mignon kielbasa fatback boudin pork rump.<br><br>Porchetta swine meatball, short ribs pork loin pancetta pork belly pork capicola ball tip corned beef leberkas ribeye prosciutto brisket. Porchetta cow biltong, kevin ground round ribeye frankfurter pork loin swine drumstick t-bone. Pig chicken meatball pancetta, leberkas shoulder kielbasa flank sirloin pork loin rump strip steak boudin cow. Pig pork chop ground round brisket. Short loin ribeye salami andouille shankle chuck pork cow bacon turkey capicola.<br><br><em>The Management</em><br><br>Photos courtesy of <a href='https://unsplash.com/'>Unsplash.com</a>.\"\n" +
                "  }\n" +
                "]";

        return memo;
    }
}
